name: base
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.6,<4
    - pip
    - numpy-base>=1.18
    - numpy>=1.18
    - scipy>=1.4.0
    - pandas>=0.25
    - dask>=2.6.0
    - imagecodecs>=2020.5.30
    - pip:
        - tifffile>=2019.7.26
        - opencv-contrib-python>=4.0
        - pyyaml>=5.3.0
